# Generated by Django 5.0.3 on 2025-03-25 00:42

import Home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='caption',
            field=models.CharField(max_length=100, verbose_name='عنوان الفيديو'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(upload_to='videos/%Y/%m/', validators=[Home.models.validate_video_size]),
        ),
    ]
