# Generated by Django 5.0.3 on 2025-05-15 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_customuser_delete_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
