# Generated by Django 5.0.3 on 2025-05-21 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Loginpage', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
